/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FormEstudiante.java
 *
 * Created on 28-nov-2011, 16:14:46
 */
package com.gps.view;

import com.gps.bean.Escuela;
import com.gps.bean.Estudiante;
import com.gps.comboboxmodel.CbModelEscuela;
import com.gps.comboboxmodel.CbModelFacultad;
import com.gps.logic.LogicEscuela;
import com.gps.logic.LogicEstudiante;
import com.gps.logic.LogicFacultad;
import com.gps.tablemodel.TableModelEstudiante;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.math.BigDecimal;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Administrador
 */
public class FormEstudiante extends javax.swing.JPanel {

    /** Creates new form FormEstudiante */
    public FormEstudiante() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombres = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        lblApPaterno = new javax.swing.JLabel();
        txtApPaterno = new javax.swing.JTextField();
        lblApMaterno = new javax.swing.JLabel();
        txtApMaterno = new javax.swing.JTextField();
        lblCodUniv = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        lblFacultad = new javax.swing.JLabel();
        lblEscuela = new javax.swing.JLabel();
        cbFacultad = new com.gps.util.JComboBoxAutocomplete();
        cbEscuela = new com.gps.util.JComboBoxAutocomplete();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        lblId = new javax.swing.JLabel();
        btnAddFacultad = new javax.swing.JButton();
        btnAddEscuela = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(FormEstudiante.class, "FormEstudiante.border.title"))); // NOI18N

        lblNombres.setText(org.openide.util.NbBundle.getMessage(FormEstudiante.class, "FormEstudiante.lblNombres.text")); // NOI18N

        txtNombres.setText(org.openide.util.NbBundle.getMessage(FormEstudiante.class, "FormEstudiante.txtNombres.text")); // NOI18N

        lblApPaterno.setText(org.openide.util.NbBundle.getMessage(FormEstudiante.class, "FormEstudiante.lblApPaterno.text")); // NOI18N

        txtApPaterno.setText(org.openide.util.NbBundle.getMessage(FormEstudiante.class, "FormEstudiante.txtApPaterno.text")); // NOI18N

        lblApMaterno.setText(org.openide.util.NbBundle.getMessage(FormEstudiante.class, "FormEstudiante.lblApMaterno.text")); // NOI18N

        txtApMaterno.setText(org.openide.util.NbBundle.getMessage(FormEstudiante.class, "FormEstudiante.txtApMaterno.text")); // NOI18N

        lblCodUniv.setText(org.openide.util.NbBundle.getMessage(FormEstudiante.class, "FormEstudiante.lblCodUniv.text")); // NOI18N

        txtCodigo.setText(org.openide.util.NbBundle.getMessage(FormEstudiante.class, "FormEstudiante.txtCodigo.text")); // NOI18N

        lblFacultad.setText(org.openide.util.NbBundle.getMessage(FormEstudiante.class, "FormEstudiante.lblFacultad.text")); // NOI18N

        lblEscuela.setText(org.openide.util.NbBundle.getMessage(FormEstudiante.class, "FormEstudiante.lblEscuela.text")); // NOI18N

        cbFacultad.setEditable(true);
        cbFacultad.setModel(cbmodfac);
        cbFacultad.addActionListener(actionListener);

        cbEscuela.setEditable(true);

        btnCancelar.setText(org.openide.util.NbBundle.getMessage(FormEstudiante.class, "FormEstudiante.btnCancelar.text")); // NOI18N
        btnCancelar.addActionListener(actionListener);

        btnGuardar.setText(org.openide.util.NbBundle.getMessage(FormEstudiante.class, "FormEstudiante.btnGuardar.text")); // NOI18N
        btnGuardar.addActionListener(actionListener);

        lblId.setText(org.openide.util.NbBundle.getMessage(FormEstudiante.class, "FormEstudiante.lblId.text")); // NOI18N

        btnAddFacultad.setText(org.openide.util.NbBundle.getMessage(FormEstudiante.class, "FormEstudiante.btnAddFacultad.text")); // NOI18N
        btnAddFacultad.setToolTipText(org.openide.util.NbBundle.getMessage(FormEstudiante.class, "FormEstudiante.btnAddFacultad.toolTipText")); // NOI18N
        btnAddFacultad.setIcon(ViewLogin.picture.getIconI());
        btnAddFacultad.addActionListener(actionListener);

        btnAddEscuela.setText(org.openide.util.NbBundle.getMessage(FormEstudiante.class, "FormEstudiante.btnAddEscuela.text")); // NOI18N
        btnAddEscuela.setToolTipText(org.openide.util.NbBundle.getMessage(FormEstudiante.class, "FormEstudiante.btnAddEscuela.toolTipText")); // NOI18N
        btnAddEscuela.setIcon(ViewLogin.picture.getIconI());
        btnAddEscuela.addActionListener(actionListener);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombres)
                            .addComponent(lblApPaterno)
                            .addComponent(lblApMaterno)
                            .addComponent(lblCodUniv))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtApMaterno, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnGuardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCancelar))
                            .addComponent(txtNombres, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                            .addComponent(txtApPaterno, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblFacultad)
                                .addGap(58, 58, 58))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblId)
                                .addGap(88, 88, 88))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblEscuela, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbFacultad, 0, 259, Short.MAX_VALUE)
                            .addComponent(cbEscuela, 0, 259, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddFacultad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAddEscuela))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombres)
                    .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblApPaterno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblApMaterno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCodUniv))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAddFacultad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbFacultad)
                    .addComponent(lblFacultad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbEscuela)
                        .addComponent(lblEscuela))
                    .addComponent(btnAddEscuela, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnGuardar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddEscuela;
    private javax.swing.JButton btnAddFacultad;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox cbEscuela;
    private javax.swing.JComboBox cbFacultad;
    private javax.swing.JLabel lblApMaterno;
    private javax.swing.JLabel lblApPaterno;
    private javax.swing.JLabel lblCodUniv;
    private javax.swing.JLabel lblEscuela;
    private javax.swing.JLabel lblFacultad;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNombres;
    private javax.swing.JTextField txtApMaterno;
    private javax.swing.JTextField txtApPaterno;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNombres;
    // End of variables declaration//GEN-END:variables
//Inicio de Atributos de clase
    private CbModelFacultad cbmodfac=new CbModelFacultad(LogicFacultad.listarFacultad(BigDecimal.ZERO));
    private CbModelEscuela cbmodesc=new CbModelEscuela();    
    private JTable tablaDatos;
    private TableModelEstudiante modeloDatos;
    private ViewEscuela panelEscuela;
    private ViewFacultad panelFacultad;    
    //Fin de Atributos de clase
    //Inicio de Constructores de clase    
    public FormEstudiante(JTable tabla,TableModelEstudiante modelo ) {
        tablaDatos=tabla;
        modeloDatos=modelo;
        tabla.setModel(modelo);
        tablaDatos.getColumnModel().getColumn(0).setMaxWidth(30);
        tablaDatos.getColumnModel().getColumn(5).setPreferredWidth(200);
        tablaDatos.getColumnModel().getColumn(6).setPreferredWidth(200);
        tablaDatos.addKeyListener(keyListener);
        tablaDatos.addMouseListener(mouseAdapter);
        initComponents();
        //btnAddEscuela.addActionListener(actionListener);
    }
    //Fin de constructores de clase
    
    //Inicio de Eventos
    ActionListener actionListener=new ActionListener(){

        @Override
        public void actionPerformed(ActionEvent e) {
            if(e.getSource().equals(cbFacultad)){ 
                try{                                    
                cbFacultad.getEditor().setItem(cbFacultad.getSelectedItem());
                cbmodesc.setData(LogicEscuela.listarEscuela(cbmodfac.getElement(cbFacultad.getSelectedIndex()).getId()));
                cbEscuela.setModel(cbmodesc);        
                cbEscuela.updateUI();    
                cbEscuela.getEditor().setItem(null);                
                }catch(Exception ex){
                    cbmodesc.setData(new ArrayList<Escuela>());
                    cbEscuela.setModel(cbmodesc);
                    cbFacultad.getEditor().setItem(null);
                    cbEscuela.getEditor().setItem(null);                
                }
            }else if(e.getSource().equals(btnGuardar)){
                mantenimiento();
            }else if(e.getSource().equals(btnCancelar)){
                cleaning();
            }/*else if(e.getSource().equals(btnAddEscuela)){
                viewPanelEscuela();
            }*/
        }        
    };
    
    MouseAdapter mouseAdapter = new MouseAdapter() {

        @Override
        public void mouseClicked(MouseEvent e) {
            if (e.getClickCount() == 2) {
                cargarDatosUpdate();
            }
        }
    };
    
    KeyListener keyListener = new KeyListener() {

        @Override
        public void keyTyped(KeyEvent e) {
        }

        @Override
        public void keyPressed(KeyEvent e) {
            if (e.getSource().equals(tablaDatos)) {
                if (e.getKeyCode() == KeyEvent.VK_DELETE) {
                    int n = JOptionPane.showConfirmDialog(null, "¿Desea en realidad eliminar el registro?", "Information", JOptionPane.YES_NO_OPTION);
                    if (n == JOptionPane.YES_OPTION) {
                        eliminar();
                    }
                }
            }
        }

        @Override
        public void keyReleased(KeyEvent e) {
        }
    };
    //Fin de Eventos
    
    //Inicio de Metodos del Negocio
    /*private void viewPanelEscuela(){
        try {
            panelEscuela.setVisible(true);
        } catch (Exception ex) {
            panelEscuela = new ViewEscuela(this);            
            panelEscuela.setTitle("Mantenimiento de Escuelas Profesionales");
            panelEscuela.pack();
            panelEscuela.setLocationRelativeTo(null);
            panelEscuela.setVisible(true);
        }
    }*/
    
    private void cargarDatosUpdate() {
        btnGuardar.setText("Actualizar");
        try {
            int fila = tablaDatos.getSelectedRow();
            int modelrow = tablaDatos.convertRowIndexToModel(fila);
            Estudiante obj = ((TableModelEstudiante) tablaDatos.getModel()).getValue(modelrow);
            lblId.setText(obj.getId().toString());
            txtNombres.setText(obj.getNombres());
            txtApPaterno.setText(obj.getAppaterno());
            txtApMaterno.setText(obj.getApmaterno());
            txtCodigo.setText(obj.getCodigouniv());
            cbFacultad.setSelectedItem(obj.getEscuela().getFacultad().getSiglas());            
            cbFacultad.getEditor().setItem(obj.getEscuela().getFacultad().getSiglas());            
            cbmodesc.setData(LogicEscuela.listarEscuela(obj.getEscuela().getFacultad().getId()));
            cbEscuela.setModel(cbmodesc);
            cbEscuela.updateUI();
            cbEscuela.getEditor().setItem(obj.getEscuela().getDescripcion());            
        } catch (Exception ex) {
            ViewApplication.mensajeEstado.setText("Error");
            ViewApplication.mensajeEstado.setIcon(ViewLogin.picture.getIconBad());
        }
    }
    
    private void eliminar() {
        int fila = tablaDatos.getSelectedRow();
        int modelrow = tablaDatos.convertRowIndexToModel(fila);
        Estudiante docente = ((TableModelEstudiante) tablaDatos.getModel()).getValue(modelrow);
        if (LogicEstudiante.eliminarEstudiante(docente.getId())) {
            ((TableModelEstudiante) tablaDatos.getModel()).borrar(modelrow);
            ViewApplication.mensajeEstado.setText("Eliminado correctamente");
            ViewApplication.mensajeEstado.setIcon(ViewLogin.picture.getIconGood());
        } else {
            ViewApplication.mensajeEstado.setText("Error");
            ViewApplication.mensajeEstado.setIcon(ViewLogin.picture.getIconBad());
        }
    }
    
    private void cleaning(){
       txtNombres.setText(null);
       txtApPaterno.setText(null);
       txtApMaterno.setText(null);
       txtCodigo.setText(null);
       btnGuardar.setText("Guardar");
       lblId.setText(null);
   }
    private void mantenimiento(){
        BigDecimal idEscuela=null;
        BigDecimal idGrado=null;        
        String nombres=null;
        String apPaterno=null;
        String apMaterno=null;    
        String codigo=null;
        BigDecimal estado=null;
        BigDecimal id=null;
        switch (btnGuardar.getText()) {
            case "Guardar":
                try{
                idEscuela=cbmodesc.getElement(cbEscuela.getSelectedIndex()).getId();                
                nombres=txtNombres.getText();
                apPaterno=txtApPaterno.getText();
                apMaterno=txtApMaterno.getText();
                codigo=txtCodigo.getText();
                estado=LogicEstudiante.registrarEstudiante(nombres, apPaterno, apMaterno,codigo,idEscuela);                
                if(estado.compareTo(BigDecimal.ONE)==0){
                    modeloDatos.setData(LogicEstudiante.listarEstudiante());
                    modeloDatos.fireTableDataChanged();
                    cleaning();
                }
                }catch(Exception ex){
                    ViewApplication.mensajeEstado.setText("Error");
                    ViewApplication.mensajeEstado.setIcon(ViewLogin.picture.getIconBad());
                }
                break;
            case "Actualizar":    
                try{
                idEscuela=cbmodesc.getElement(cbEscuela.getSelectedIndex()).getId();                
                nombres=txtNombres.getText();
                apPaterno=txtApPaterno.getText();
                apMaterno=txtApMaterno.getText();
                codigo=txtCodigo.getText();
                id=BigDecimal.valueOf(Double.valueOf(lblId.getText()));
                estado=LogicEstudiante.actualizarEstudiante(id,nombres, apPaterno, apMaterno,codigo,idEscuela);                
                if (estado.compareTo(BigDecimal.valueOf(2)) == 0) {
                    modeloDatos.setData(LogicEstudiante.listarEstudiante());
                    modeloDatos.fireTableDataChanged();                    
                    cleaning();
                }
                }catch(Exception ex){
                    ViewApplication.mensajeEstado.setText("Error");
                    ViewApplication.mensajeEstado.setIcon(ViewLogin.picture.getIconBad());
                }
                break;
        }
    }
    //Fin de Metodos del Negocio

    public CbModelEscuela getCbmodesc() {
        return cbmodesc;
    }

    public void setCbmodesc(CbModelEscuela cbmodesc) {
        this.cbmodesc = cbmodesc;
    }

    public CbModelFacultad getCbmodfac() {
        return cbmodfac;
    }

    public void setCbmodfac(CbModelFacultad cbmodfac) {
        this.cbmodfac = cbmodfac;
    }

    public TableModelEstudiante getModeloDatos() {
        return modeloDatos;
    }

    public void setModeloDatos(TableModelEstudiante modeloDatos) {
        this.modeloDatos = modeloDatos;
    }

    public ViewEscuela getPanelEscuela() {
        return panelEscuela;
    }

    public void setPanelEscuela(ViewEscuela panelEscuela) {
        this.panelEscuela = panelEscuela;
    }

    public ViewFacultad getPanelFacultad() {
        return panelFacultad;
    }

    public void setPanelFacultad(ViewFacultad panelFacultad) {
        this.panelFacultad = panelFacultad;
    }

    public JTable getTablaDatos() {
        return tablaDatos;
    }

    public void setTablaDatos(JTable tablaDatos) {
        this.tablaDatos = tablaDatos;
    }

    public ActionListener getActionListener() {
        return actionListener;
    }

    public void setActionListener(ActionListener actionListener) {
        this.actionListener = actionListener;
    }

    public JButton getBtnAddEscuela() {
        return btnAddEscuela;
    }

    public void setBtnAddEscuela(JButton btnAddEscuela) {
        this.btnAddEscuela = btnAddEscuela;
    }

    public JButton getBtnAddFacultad() {
        return btnAddFacultad;
    }

    public void setBtnAddFacultad(JButton btnAddFacultad) {
        this.btnAddFacultad = btnAddFacultad;
    }

    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    public void setBtnCancelar(JButton btnCancelar) {
        this.btnCancelar = btnCancelar;
    }

    public JButton getBtnGuardar() {
        return btnGuardar;
    }

    public void setBtnGuardar(JButton btnGuardar) {
        this.btnGuardar = btnGuardar;
    }

    public JComboBox getCbEscuela() {
        return cbEscuela;
    }

    public void setCbEscuela(JComboBox cbEscuela) {
        this.cbEscuela = cbEscuela;
    }

    public JComboBox getCbFacultad() {
        return cbFacultad;
    }

    public void setCbFacultad(JComboBox cbFacultad) {
        this.cbFacultad = cbFacultad;
    }

    public KeyListener getKeyListener() {
        return keyListener;
    }

    public void setKeyListener(KeyListener keyListener) {
        this.keyListener = keyListener;
    }

    public JLabel getLblApMaterno() {
        return lblApMaterno;
    }

    public void setLblApMaterno(JLabel lblApMaterno) {
        this.lblApMaterno = lblApMaterno;
    }

    public JLabel getLblApPaterno() {
        return lblApPaterno;
    }

    public void setLblApPaterno(JLabel lblApPaterno) {
        this.lblApPaterno = lblApPaterno;
    }

    public JLabel getLblCodUniv() {
        return lblCodUniv;
    }

    public void setLblCodUniv(JLabel lblCodUniv) {
        this.lblCodUniv = lblCodUniv;
    }

    public JLabel getLblEscuela() {
        return lblEscuela;
    }

    public void setLblEscuela(JLabel lblEscuela) {
        this.lblEscuela = lblEscuela;
    }

    public JLabel getLblFacultad() {
        return lblFacultad;
    }

    public void setLblFacultad(JLabel lblFacultad) {
        this.lblFacultad = lblFacultad;
    }

    public JLabel getLblId() {
        return lblId;
    }

    public void setLblId(JLabel lblId) {
        this.lblId = lblId;
    }

    public JLabel getLblNombres() {
        return lblNombres;
    }

    public void setLblNombres(JLabel lblNombres) {
        this.lblNombres = lblNombres;
    }

    public MouseAdapter getMouseAdapter() {
        return mouseAdapter;
    }

    public void setMouseAdapter(MouseAdapter mouseAdapter) {
        this.mouseAdapter = mouseAdapter;
    }

    public JTextField getTxtApMaterno() {
        return txtApMaterno;
    }

    public void setTxtApMaterno(JTextField txtApMaterno) {
        this.txtApMaterno = txtApMaterno;
    }

    public JTextField getTxtApPaterno() {
        return txtApPaterno;
    }

    public void setTxtApPaterno(JTextField txtApPaterno) {
        this.txtApPaterno = txtApPaterno;
    }

    public JTextField getTxtCodigo() {
        return txtCodigo;
    }

    public void setTxtCodigo(JTextField txtCodigo) {
        this.txtCodigo = txtCodigo;
    }

    public JTextField getTxtNombres() {
        return txtNombres;
    }

    public void setTxtNombres(JTextField txtNombres) {
        this.txtNombres = txtNombres;
    }
    
    
    
}
