/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FormDecano.java
 *
 * Created on 30-nov-2011, 0:30:01
 */
package com.gps.view;

import com.gps.bean.Escuela;
import com.gps.comboboxmodel.CbModelEscuela;
import com.gps.comboboxmodel.CbModelFacuDecano;
import com.gps.comboboxmodel.CbModelFacultad;
import com.gps.logic.LogicEscuela;
import com.gps.logic.LogicFacultad;
import com.gps.tablemodel.TableModelProyecto;
import com.toedter.calendar.JDateChooser;
import com.toedter.calendar.JSpinnerDateEditor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Administrador
 */
public class FormProyecto extends javax.swing.JPanel {

    /** Creates new form FormDecano */
    public FormProyecto() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblFacultad = new javax.swing.JLabel();
        lblDocente = new javax.swing.JLabel();
        txtSolicitante = new javax.swing.JTextField();
        btnAddSolicitante = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblId = new javax.swing.JLabel();
        txtProyecto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        panelFecha = new javax.swing.JPanel();

        setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(FormProyecto.class, "FormProyecto.border.title_1"))); // NOI18N
        setLayout(new java.awt.GridBagLayout());

        lblFacultad.setText(org.openide.util.NbBundle.getMessage(FormProyecto.class, "FormProyecto.lblFacultad.text_1")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(lblFacultad, gridBagConstraints);

        lblDocente.setText(org.openide.util.NbBundle.getMessage(FormProyecto.class, "FormProyecto.lblDocente.text_1")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(lblDocente, gridBagConstraints);

        txtSolicitante.setColumns(20);
        txtSolicitante.setText(org.openide.util.NbBundle.getMessage(FormProyecto.class, "FormProyecto.txtSolicitante.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(txtSolicitante, gridBagConstraints);

        btnAddSolicitante.setText(org.openide.util.NbBundle.getMessage(FormProyecto.class, "FormProyecto.btnAddSolicitante.text")); // NOI18N
        btnAddSolicitante.setToolTipText(org.openide.util.NbBundle.getMessage(FormProyecto.class, "FormProyecto.btnAddSolicitante.toolTipText")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(btnAddSolicitante, gridBagConstraints);

        btnGuardar.setText(org.openide.util.NbBundle.getMessage(FormProyecto.class, "FormProyecto.btnGuardar.text_1")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(btnGuardar, gridBagConstraints);

        btnCancelar.setText(org.openide.util.NbBundle.getMessage(FormProyecto.class, "FormProyecto.btnCancelar.text_1")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(btnCancelar, gridBagConstraints);

        lblId.setText(org.openide.util.NbBundle.getMessage(FormProyecto.class, "FormProyecto.lblId.text_1")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(lblId, gridBagConstraints);

        txtProyecto.setText(org.openide.util.NbBundle.getMessage(FormProyecto.class, "FormProyecto.txtProyecto.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(txtProyecto, gridBagConstraints);

        jLabel1.setText(org.openide.util.NbBundle.getMessage(FormProyecto.class, "FormProyecto.jLabel1.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(jLabel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(panelFecha, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddSolicitante;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblDocente;
    private javax.swing.JLabel lblFacultad;
    private javax.swing.JLabel lblId;
    private javax.swing.JPanel panelFecha;
    private javax.swing.JTextField txtProyecto;
    private javax.swing.JTextField txtSolicitante;
    // End of variables declaration//GEN-END:variables
    //Inicio de Atributos de clase            
    private JTable tablaDatos;
    private TableModelProyecto modeloDatos;
    private JDateChooser fechainicio;    
    private JSpinnerDateEditor txtfechainicio = new JSpinnerDateEditor();    
    private CbModelFacuDecano cbmodfac=new CbModelFacuDecano(LogicFacultad.listarFacultad(BigDecimal.ZERO));
    private CbModelEscuela cbmodesc=new CbModelEscuela();    
    //Fin de Atributos de clase
    
    public FormProyecto(JTable tabla,TableModelProyecto modelo ) {
        tablaDatos=tabla;
        modeloDatos=modelo;
        tabla.setModel(modelo);
        tablaDatos.getColumnModel().getColumn(0).setMaxWidth(50);                
        initComponents();        
        txtSolicitante.setEditable(false);
        btnAddSolicitante.setIcon(ViewLogin.picture.getIconI());
        fechainicio = new JDateChooser(txtfechainicio);        
        fechainicio.setDate(new Date());        
        panelFecha.add(fechainicio);
    }
        

    public JButton getBtnAddSolicitante() {
        return btnAddSolicitante;
    }

    public void setBtnAddSolicitante(JButton btnAddSolicitante) {
        this.btnAddSolicitante = btnAddSolicitante;
    }

    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    public void setBtnCancelar(JButton btnCancelar) {
        this.btnCancelar = btnCancelar;
    }

    public JButton getBtnGuardar() {
        return btnGuardar;
    }

    public void setBtnGuardar(JButton btnGuardar) {
        this.btnGuardar = btnGuardar;
    }

    public JLabel getLblDocente() {
        return lblDocente;
    }

    public void setLblDocente(JLabel lblDocente) {
        this.lblDocente = lblDocente;
    }

    public JLabel getLblFacultad() {
        return lblFacultad;
    }

    public void setLblFacultad(JLabel lblFacultad) {
        this.lblFacultad = lblFacultad;
    }

    public JLabel getLblId() {
        return lblId;
    }

    public void setLblId(JLabel lblId) {
        this.lblId = lblId;
    }

    public TableModelProyecto getModeloDatos() {
        return modeloDatos;
    }

    public void setModeloDatos(TableModelProyecto modeloDatos) {
        this.modeloDatos = modeloDatos;
    }

    public JTable getTablaDatos() {
        return tablaDatos;
    }

    public void setTablaDatos(JTable tablaDatos) {
        this.tablaDatos = tablaDatos;
    }

    public JTextField getTxtProyecto() {
        return txtProyecto;
    }

    public void setTxtProyecto(JTextField txtProyecto) {
        this.txtProyecto = txtProyecto;
    }

    public JTextField getTxtSolicitante() {
        return txtSolicitante;
    }

    public void setTxtSolicitante(JTextField txtSolicitante) {
        this.txtSolicitante = txtSolicitante;
    }

    public JDateChooser getFechainicio() {
        return fechainicio;
    }

    public void setFechainicio(JDateChooser fechainicio) {
        this.fechainicio = fechainicio;
    }

    public JSpinnerDateEditor getTxtfechainicio() {
        return txtfechainicio;
    }

    public void setTxtfechainicio(JSpinnerDateEditor txtfechainicio) {
        this.txtfechainicio = txtfechainicio;
    }

    

    public CbModelEscuela getCbmodesc() {
        return cbmodesc;
    }

    public void setCbmodesc(CbModelEscuela cbmodesc) {
        this.cbmodesc = cbmodesc;
    }

    public CbModelFacuDecano getCbmodfac() {
        return cbmodfac;
    }

    public void setCbmodfac(CbModelFacuDecano cbmodfac) {
        this.cbmodfac = cbmodfac;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }
    

    public JPanel getPanelFecha() {
        return panelFecha;
    }

    public void setPanelFecha(JPanel panelFecha) {
        this.panelFecha = panelFecha;
    }
    
    
    
}
