/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FormDocente.java
 *
 * Created on 01-oct-2011, 21:44:45
 */
package com.gps.view;

import com.gps.bean.Docente;
import com.gps.bean.Escuela;
import com.gps.comboboxmodel.CbModelEscuela;
import com.gps.comboboxmodel.CbModelFacultad;
import com.gps.comboboxmodel.CbModelGrado;
import com.gps.logic.LogicDocente;
import com.gps.logic.LogicEscuela;
import com.gps.logic.LogicFacultad;
import com.gps.logic.LogicGrado;
import com.gps.tablemodel.TableModelDocente;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.math.BigDecimal;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Administrador
 */
public class FormDocente extends javax.swing.JPanel {                                        
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombres = new javax.swing.JLabel();
        lblApPaterno = new javax.swing.JLabel();
        lblApMaterno = new javax.swing.JLabel();
        lblFacultad = new javax.swing.JLabel();
        lblEscuela = new javax.swing.JLabel();
        lblGrado = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        txtApPaterno = new javax.swing.JTextField();
        txtApMaterno = new javax.swing.JTextField();
        cbFacultad = new com.gps.util.JComboBoxAutocomplete();
        cbEscuela = new com.gps.util.JComboBoxAutocomplete();
        cbGrado = new com.gps.util.JComboBoxAutocomplete();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnAddFacultad = new javax.swing.JButton();
        btnAddEscuela = new javax.swing.JButton();
        btnAddGrado = new javax.swing.JButton();
        lblId = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(FormDocente.class, "FormDocente.border.title"))); // NOI18N

        lblNombres.setText(org.openide.util.NbBundle.getMessage(FormDocente.class, "FormDocente.lblNombres.text")); // NOI18N

        lblApPaterno.setText(org.openide.util.NbBundle.getMessage(FormDocente.class, "FormDocente.lblApPaterno.text")); // NOI18N

        lblApMaterno.setText(org.openide.util.NbBundle.getMessage(FormDocente.class, "FormDocente.lblApMaterno.text")); // NOI18N

        lblFacultad.setText(org.openide.util.NbBundle.getMessage(FormDocente.class, "FormDocente.lblFacultad.text")); // NOI18N

        lblEscuela.setText(org.openide.util.NbBundle.getMessage(FormDocente.class, "FormDocente.lblEscuela.text")); // NOI18N

        lblGrado.setText(org.openide.util.NbBundle.getMessage(FormDocente.class, "FormDocente.lblGrado.text")); // NOI18N

        txtNombres.setText(org.openide.util.NbBundle.getMessage(FormDocente.class, "FormDocente.txtNombres.text")); // NOI18N

        txtApPaterno.setText(org.openide.util.NbBundle.getMessage(FormDocente.class, "FormDocente.txtApPaterno.text")); // NOI18N

        txtApMaterno.setText(org.openide.util.NbBundle.getMessage(FormDocente.class, "FormDocente.txtApMaterno.text")); // NOI18N

        cbFacultad.setEditable(true);
        cbFacultad.setModel(cbmodfac);
        cbFacultad.addActionListener(actionListener);

        cbEscuela.setEditable(true);

        cbGrado.setEditable(true);
        cbGrado.setModel(cbmodgrad);

        btnGuardar.setText(org.openide.util.NbBundle.getMessage(FormDocente.class, "FormDocente.btnGuardar.text")); // NOI18N
        btnGuardar.addActionListener(actionListener);

        btnCancelar.setText(org.openide.util.NbBundle.getMessage(FormDocente.class, "FormDocente.btnCancelar.text")); // NOI18N
        btnCancelar.addActionListener(actionListener);

        btnAddFacultad.setText(org.openide.util.NbBundle.getMessage(FormDocente.class, "FormDocente.btnAddFacultad.text")); // NOI18N
        btnAddFacultad.setToolTipText(org.openide.util.NbBundle.getMessage(FormDocente.class, "FormDocente.btnAddFacultad.toolTipText")); // NOI18N
        btnAddFacultad.setIcon(ViewLogin.picture.getIconI());
        btnAddFacultad.addActionListener(actionListener);

        btnAddEscuela.setText(org.openide.util.NbBundle.getMessage(FormDocente.class, "FormDocente.btnAddEscuela.text")); // NOI18N
        btnAddEscuela.setToolTipText(org.openide.util.NbBundle.getMessage(FormDocente.class, "FormDocente.btnAddEscuela.toolTipText")); // NOI18N
        btnAddEscuela.setIcon(ViewLogin.picture.getIconI());
        btnAddEscuela.addActionListener(actionListener);

        btnAddGrado.setText(org.openide.util.NbBundle.getMessage(FormDocente.class, "FormDocente.btnAddGrado.text")); // NOI18N
        btnAddGrado.setToolTipText(org.openide.util.NbBundle.getMessage(FormDocente.class, "FormDocente.btnAddGrado.toolTipText")); // NOI18N
        btnAddGrado.setIcon(ViewLogin.picture.getIconI());
        btnAddGrado.addActionListener(actionListener);

        lblId.setText(org.openide.util.NbBundle.getMessage(FormDocente.class, "FormDocente.lblId.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblApMaterno)
                    .addComponent(lblFacultad)
                    .addComponent(lblEscuela)
                    .addComponent(lblNombres)
                    .addComponent(lblApPaterno)
                    .addComponent(lblGrado)
                    .addComponent(lblId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGuardar)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar))
                    .addComponent(txtApPaterno, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                    .addComponent(cbFacultad, javax.swing.GroupLayout.Alignment.LEADING, 0, 258, Short.MAX_VALUE)
                    .addComponent(cbGrado, javax.swing.GroupLayout.Alignment.LEADING, 0, 258, Short.MAX_VALUE)
                    .addComponent(txtApMaterno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                    .addComponent(txtNombres, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                    .addComponent(cbEscuela, 0, 258, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAddGrado, 0, 0, Short.MAX_VALUE)
                    .addComponent(btnAddEscuela, 0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(btnAddFacultad, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombres)
                    .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApPaterno)
                    .addComponent(txtApPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApMaterno)
                    .addComponent(txtApMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnAddFacultad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbFacultad)
                    .addComponent(lblFacultad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAddEscuela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(cbEscuela, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblEscuela)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAddGrado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cbGrado)
                        .addComponent(lblGrado)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnGuardar)
                        .addComponent(lblId)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddEscuela;
    private javax.swing.JButton btnAddFacultad;
    private javax.swing.JButton btnAddGrado;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox cbEscuela;
    private javax.swing.JComboBox cbFacultad;
    private javax.swing.JComboBox cbGrado;
    private javax.swing.JLabel lblApMaterno;
    private javax.swing.JLabel lblApPaterno;
    private javax.swing.JLabel lblEscuela;
    private javax.swing.JLabel lblFacultad;
    private javax.swing.JLabel lblGrado;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNombres;
    private javax.swing.JTextField txtApMaterno;
    private javax.swing.JTextField txtApPaterno;
    private javax.swing.JTextField txtNombres;
    // End of variables declaration//GEN-END:variables
    //Inicio de Atributos de clase
    private CbModelFacultad cbmodfac=new CbModelFacultad(LogicFacultad.listarFacultad(BigDecimal.ZERO));
    private CbModelEscuela cbmodesc=new CbModelEscuela();
    private CbModelGrado cbmodgrad=new CbModelGrado(LogicGrado.listarGrado());
    private JTable tablaDatos;
    private TableModelDocente modeloDatos;
    private ViewEscuela panelEscuela;
    private ViewFacultad panelFacultad;
    private ViewGrado panelGrado;
    //Fin de Atributos de clase
    
    //Inicio de Constructores de clase    
    public FormDocente(JTable tabla,TableModelDocente modelo ) {
        tablaDatos=tabla;
        modeloDatos=modelo;
        tabla.setModel(modelo);
        tablaDatos.getColumnModel().getColumn(0).setMaxWidth(30);
        tablaDatos.getColumnModel().getColumn(5).setPreferredWidth(200);
        tablaDatos.getColumnModel().getColumn(6).setPreferredWidth(200);
        tablaDatos.addKeyListener(keyListener);
        tablaDatos.addMouseListener(mouseAdapter);
        initComponents();
        //btnAddEscuela.addActionListener(actionListener);
    }
    //Fin de constructores de clase
    
    //Inicio de Eventos
    ActionListener actionListener=new ActionListener(){

        @Override
        public void actionPerformed(ActionEvent e) {
            if(e.getSource().equals(cbFacultad)){ 
                try{                                    
                cbFacultad.getEditor().setItem(cbFacultad.getSelectedItem());
                cbmodesc.setData(LogicEscuela.listarEscuela(cbmodfac.getElement(cbFacultad.getSelectedIndex()).getId()));
                cbEscuela.setModel(cbmodesc);        
                cbEscuela.updateUI();    
                cbEscuela.getEditor().setItem(null);                
                }catch(Exception ex){
                    cbmodesc.setData(new ArrayList<Escuela>());
                    cbEscuela.setModel(cbmodesc);
                    cbFacultad.getEditor().setItem(null);
                    cbEscuela.getEditor().setItem(null);                
                }
            }else if(e.getSource().equals(btnGuardar)){
                mantenimiento();
            }else if(e.getSource().equals(btnCancelar)){
                cleaning();
            }/*else if(e.getSource().equals(btnAddEscuela)){
                viewPanelEscuela();
            }*/
        }        
    };
    
    MouseAdapter mouseAdapter = new MouseAdapter() {

        @Override
        public void mouseClicked(MouseEvent e) {
            if (e.getClickCount() == 2) {
                cargarDatosUpdate();
            }
        }
    };
    
    KeyListener keyListener = new KeyListener() {

        @Override
        public void keyTyped(KeyEvent e) {
        }

        @Override
        public void keyPressed(KeyEvent e) {
            if (e.getSource().equals(tablaDatos)) {
                if (e.getKeyCode() == KeyEvent.VK_DELETE) {
                    int n = JOptionPane.showConfirmDialog(null, "¿Desea en realidad eliminar el registro?", "Information", JOptionPane.YES_NO_OPTION);
                    if (n == JOptionPane.YES_OPTION) {
                        eliminar();
                    }
                }
            }
        }

        @Override
        public void keyReleased(KeyEvent e) {
        }
    };
    //Fin de Eventos
    
    //Inicio de Metodos del Negocio
    /*private void viewPanelEscuela(){
        try {
            panelEscuela.setVisible(true);
        } catch (Exception ex) {
            panelEscuela = new ViewEscuela(this);            
            panelEscuela.setTitle("Mantenimiento de Escuelas Profesionales");
            panelEscuela.pack();
            panelEscuela.setLocationRelativeTo(null);
            panelEscuela.setVisible(true);
        }
    }*/
    
    private void cargarDatosUpdate() {
        btnGuardar.setText("Actualizar");
        try {
            int fila = tablaDatos.getSelectedRow();
            int modelrow = tablaDatos.convertRowIndexToModel(fila);
            Docente obj = ((TableModelDocente) tablaDatos.getModel()).getValue(modelrow);
            lblId.setText(obj.getId().toString());
            txtNombres.setText(obj.getNombres());
            txtApPaterno.setText(obj.getAppaterno());
            txtApMaterno.setText(obj.getApmaterno());
            cbFacultad.setSelectedItem(obj.getEscuela().getFacultad().getSiglas());            
            cbFacultad.getEditor().setItem(obj.getEscuela().getFacultad().getSiglas());            
            cbmodesc.setData(LogicEscuela.listarEscuela(obj.getEscuela().getFacultad().getId()));
            cbEscuela.setModel(cbmodesc);
            cbEscuela.updateUI();
            cbEscuela.getEditor().setItem(obj.getEscuela().getDescripcion());
            cbGrado.setSelectedItem(obj.getGrado().getDescripcion());
            cbGrado.getEditor().setItem(obj.getGrado().getDescripcion());
        } catch (Exception ex) {
            ViewApplication.mensajeEstado.setText("Error");
            ViewApplication.mensajeEstado.setIcon(ViewLogin.picture.getIconBad());
        }
    }
    
    private void eliminar() {
        int fila = tablaDatos.getSelectedRow();
        int modelrow = tablaDatos.convertRowIndexToModel(fila);
        Docente docente = ((TableModelDocente) tablaDatos.getModel()).getValue(modelrow);
        if (LogicDocente.eliminarDocente(docente.getId())) {
            ((TableModelDocente) tablaDatos.getModel()).borrar(modelrow);
            ViewApplication.mensajeEstado.setText("Eliminado correctamente");
            ViewApplication.mensajeEstado.setIcon(ViewLogin.picture.getIconGood());
        } else {
            ViewApplication.mensajeEstado.setText("Error");
            ViewApplication.mensajeEstado.setIcon(ViewLogin.picture.getIconBad());
        }
    }
    
    private void cleaning(){
       txtNombres.setText(null);
       txtApPaterno.setText(null);
       txtApMaterno.setText(null);
       btnGuardar.setText("Guardar");
       lblId.setText(null);
   }
    private void mantenimiento(){
        BigDecimal idEscuela=null;
        BigDecimal idGrado=null;        
        String nombres=null;
        String apPaterno=null;
        String apMaterno=null;        
        BigDecimal estado=null;
        BigDecimal id=null;
        switch (btnGuardar.getText()) {
            case "Guardar":
                try{
                idEscuela=cbmodesc.getElement(cbEscuela.getSelectedIndex()).getId();
                idGrado=cbmodgrad.getElement(cbGrado.getSelectedIndex()).getId();
                nombres=txtNombres.getText();
                apPaterno=txtApPaterno.getText();
                apMaterno=txtApMaterno.getText();
                estado=LogicDocente.registrarDocente(nombres, apPaterno, apMaterno, idEscuela, idGrado);                
                if(estado.compareTo(BigDecimal.ONE)==0){
                    modeloDatos.setData(LogicDocente.listarDocente(BigDecimal.ZERO));
                    modeloDatos.fireTableDataChanged();
                    cleaning();
                }
                }catch(Exception ex){
                    ViewApplication.mensajeEstado.setText("Error");
                    ViewApplication.mensajeEstado.setIcon(ViewLogin.picture.getIconBad());
                }
                break;
            case "Actualizar":    
                try{
                idEscuela=cbmodesc.getElement(cbEscuela.getSelectedIndex()).getId();
                idGrado=cbmodgrad.getElement(cbGrado.getSelectedIndex()).getId();
                nombres=txtNombres.getText();
                apPaterno=txtApPaterno.getText();
                apMaterno=txtApMaterno.getText();
                id=BigDecimal.valueOf(Double.valueOf(lblId.getText()));
                estado=LogicDocente.actualizarDocente(id,nombres, apPaterno, apMaterno, idEscuela, idGrado);                
                if (estado.compareTo(BigDecimal.valueOf(2)) == 0) {
                    modeloDatos.setData(LogicDocente.listarDocente(BigDecimal.ZERO));
                    modeloDatos.fireTableDataChanged();                    
                    cleaning();
                }
                }catch(Exception ex){
                    ViewApplication.mensajeEstado.setText("Error");
                    ViewApplication.mensajeEstado.setIcon(ViewLogin.picture.getIconBad());
                }
                break;
        }
    }
    //Fin de Metodos del Negocio
    
    //Inicio de getters y setters
    public ActionListener getActionListener() {
        return actionListener;
    }

    public void setActionListener(ActionListener actionListener) {
        this.actionListener = actionListener;
    }

    public JButton getBtnAddEscuela() {
        return btnAddEscuela;
    }

    public void setBtnAddEscuela(JButton btnAddEscuela) {
        this.btnAddEscuela = btnAddEscuela;
    }

    public JButton getBtnAddFacultad() {
        return btnAddFacultad;
    }

    public void setBtnAddFacultad(JButton btnAddFacultad) {
        this.btnAddFacultad = btnAddFacultad;
    }

    public JButton getBtnAddGrado() {
        return btnAddGrado;
    }

    public void setBtnAddGrado(JButton btnAddGrado) {
        this.btnAddGrado = btnAddGrado;
    }

    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    public void setBtnCancelar(JButton btnCancelar) {
        this.btnCancelar = btnCancelar;
    }

    public JButton getBtnGuardar() {
        return btnGuardar;
    }

    public void setBtnGuardar(JButton btnGuardar) {
        this.btnGuardar = btnGuardar;
    }

    public JComboBox getCbEscuela() {
        return cbEscuela;
    }

    public void setCbEscuela(JComboBox cbEscuela) {
        this.cbEscuela = cbEscuela;
    }

    public JComboBox getCbFacultad() {
        return cbFacultad;
    }

    public void setCbFacultad(JComboBox cbFacultad) {
        this.cbFacultad = cbFacultad;
    }

    public JComboBox getCbGrado() {
        return cbGrado;
    }

    public void setCbGrado(JComboBox cbGrado) {
        this.cbGrado = cbGrado;
    }

    public CbModelEscuela getCbmodesc() {
        return cbmodesc;
    }

    public void setCbmodesc(CbModelEscuela cbmodesc) {
        this.cbmodesc = cbmodesc;
    }

    public CbModelFacultad getCbmodfac() {
        return cbmodfac;
    }

    public void setCbmodfac(CbModelFacultad cbmodfac) {
        this.cbmodfac = cbmodfac;
    }

    public CbModelGrado getCbmodgrad() {
        return cbmodgrad;
    }

    public void setCbmodgrad(CbModelGrado cbmodgrad) {
        this.cbmodgrad = cbmodgrad;
    }

    public JLabel getLblApMaterno() {
        return lblApMaterno;
    }

    public void setLblApMaterno(JLabel lblApMaterno) {
        this.lblApMaterno = lblApMaterno;
    }

    public JLabel getLblApPaterno() {
        return lblApPaterno;
    }

    public void setLblApPaterno(JLabel lblApPaterno) {
        this.lblApPaterno = lblApPaterno;
    }

    public JLabel getLblEscuela() {
        return lblEscuela;
    }

    public void setLblEscuela(JLabel lblEscuela) {
        this.lblEscuela = lblEscuela;
    }

    public JLabel getLblFacultad() {
        return lblFacultad;
    }

    public void setLblFacultad(JLabel lblFacultad) {
        this.lblFacultad = lblFacultad;
    }

    public JLabel getLblGrado() {
        return lblGrado;
    }

    public void setLblGrado(JLabel lblGrado) {
        this.lblGrado = lblGrado;
    }

    public JLabel getLblNombres() {
        return lblNombres;
    }

    public void setLblNombres(JLabel lblNombres) {
        this.lblNombres = lblNombres;
    }

    public JTextField getTxtApMaterno() {
        return txtApMaterno;
    }

    public void setTxtApMaterno(JTextField txtApMaterno) {
        this.txtApMaterno = txtApMaterno;
    }

    public JTextField getTxtApPaterno() {
        return txtApPaterno;
    }

    public void setTxtApPaterno(JTextField txtApPaterno) {
        this.txtApPaterno = txtApPaterno;
    }

    public JTextField getTxtNombres() {
        return txtNombres;
    }

    public void setTxtNombres(JTextField txtNombres) {
        this.txtNombres = txtNombres;
    }

    public JLabel getLblId() {
        return lblId;
    }

    public void setLblId(JLabel lblId) {
        this.lblId = lblId;
    }
            

    public KeyListener getKeyListener() {
        return keyListener;
    }

    public void setKeyListener(KeyListener keyListener) {
        this.keyListener = keyListener;
    }

    public TableModelDocente getModeloDatos() {
        return modeloDatos;
    }

    public void setModeloDatos(TableModelDocente modeloDatos) {
        this.modeloDatos = modeloDatos;
    }

    public MouseAdapter getMouseAdapter() {
        return mouseAdapter;
    }

    public void setMouseAdapter(MouseAdapter mouseAdapter) {
        this.mouseAdapter = mouseAdapter;
    }

    public ViewEscuela getPanelEscuela() {
        return panelEscuela;
    }

    public void setPanelEscuela(ViewEscuela panelEscuela) {
        this.panelEscuela = panelEscuela;
    }

    public JTable getTablaDatos() {
        return tablaDatos;
    }

    public void setTablaDatos(JTable tablaDatos) {
        this.tablaDatos = tablaDatos;
    }
                
    public ViewFacultad getPanelFacultad() {
        return panelFacultad;
    }

    public void setPanelFacultad(ViewFacultad panelFacultad) {
        this.panelFacultad = panelFacultad;
    }            

    public ViewGrado getPanelGrado() {
        return panelGrado;
    }

    public void setPanelGrado(ViewGrado panelGrado) {
        this.panelGrado = panelGrado;
    }
    
    
    
    //Fin de getters y setters
}
