/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmInfProyecto.java
 *
 * Created on 02-dic-2011, 6:50:17
 */
package com.gps.view;

import com.gps.tablemodel.TableModelAlumno;
import com.gps.tablemodel.TableModelDocumento;
import com.gps.tablemodel.TableModelEstadoProy;
import com.gps.tablemodel.TableModelProfesor;
import com.gps.util.CellEditorAnnoCurso;
import com.gps.util.CellEditorCalendar;
import com.gps.util.CellEditorCbEstado;
import com.gps.util.CellEditorCbTipoDoc;
import com.gps.util.CellRedenderImage;
import com.gps.util.CellRendererImageEstado;
import javax.swing.JButton;
import javax.swing.JTabbedPane;

/**
 *
 * @author Administrador
 */
public class FrmInfProyecto extends javax.swing.JPanel {

    /** Creates new form FrmInfProyecto */
    public FrmInfProyecto() {
        initComponents();   
        
        tabContenedor.addTab("Documentos",ViewLogin.picture.getIconDocumento16(),panelDocumentos);
        tabContenedor.addTab("Estudiantes",ViewLogin.picture.getIconEstudiante16(),panelEstudiantes);
        tabContenedor.addTab("Docentes",ViewLogin.picture.getIconDocente16(),panelDocentes);
        tabContenedor.addTab("Estados",ViewLogin.picture.getIconEstado16(),panelEstados);
        btnAddDoc.setToolTipText("Agregar nuevo registro");
        btnCommitDoc.setToolTipText("Confirmar operaciones");
        btnRollbackDoc.setToolTipText("Actualizar");
        btnAddDoce.setToolTipText("Agregar nuevo registro");
        btnCommitDoce.setToolTipText("Confirmar operaciones");
        btnRollbackDoce.setToolTipText("Actualizar");
        btnAddEst.setToolTipText("Agregar nuevo registro");
        btnCommitEst.setToolTipText("Confirmar operaciones");
        btnRollbackEst.setToolTipText("Actualizar");
        btnAddEsta.setToolTipText("Agregar nuevo registro");
        btnCommitEsta.setToolTipText("Confirmar operaciones");
        btnRollbackEsta.setToolTipText("Actualizar");
        panelDocumentos.getBarraBusqueda().add(btnAddDoc);
        panelDocumentos.getBarraBusqueda().add(btnCommitDoc);
        panelDocumentos.getBarraBusqueda().add(btnRollbackDoc);
        panelDocentes.getBarraBusqueda().add(btnAddDoce);
        panelDocentes.getBarraBusqueda().add(btnCommitDoce);
        panelDocentes.getBarraBusqueda().add(btnRollbackDoce);
        panelEstudiantes.getBarraBusqueda().add(btnAddEst);
        panelEstudiantes.getBarraBusqueda().add(btnCommitEst);
        panelEstudiantes.getBarraBusqueda().add(btnRollbackEst);
        panelEstados.getBarraBusqueda().add(btnAddEsta);
        panelEstados.getBarraBusqueda().add(btnCommitEsta);
        panelEstados.getBarraBusqueda().add(btnRollbackEsta);      
        modeldoc.setTablaDatos(panelDocumentos.getTablaDatos()); 
        modelalum.setTablaDatos(panelEstudiantes.getTablaDatos());
        panelDocumentos.getTablaDatos().setModel(modeldoc);
        panelEstudiantes.getTablaDatos().setModel(modelalum);
        panelDocentes.getTablaDatos().setModel(modelprof);
        panelEstados.getTablaDatos().setModel(modelestproy);
        panelDocumentos.getTablaDatos().getColumnModel().getColumn(0).setMaxWidth(20);
        panelDocumentos.getTablaDatos().getColumnModel().getColumn(0).setCellRenderer(new CellRedenderImage());        
        panelDocumentos.getTablaDatos().getColumnModel().getColumn(1).setCellEditor(new CellEditorCbTipoDoc());
        panelDocumentos.getTablaDatos().getColumnModel().getColumn(5).setCellEditor(new CellEditorCalendar());
        panelEstudiantes.getTablaDatos().getColumnModel().getColumn(0).setMaxWidth(20);
        panelEstudiantes.getTablaDatos().getColumnModel().getColumn(0).setCellRenderer(new CellRedenderImage());        
        panelDocentes.getTablaDatos().getColumnModel().getColumn(0).setMaxWidth(20);
        panelDocentes.getTablaDatos().getColumnModel().getColumn(0).setCellRenderer(new CellRedenderImage());        
        panelEstados.getTablaDatos().getColumnModel().getColumn(0).setMaxWidth(20);
        panelEstados.getTablaDatos().getColumnModel().getColumn(1).setMaxWidth(20);
        panelEstados.getTablaDatos().getColumnModel().getColumn(0).setCellRenderer(new CellRedenderImage());        
        panelEstados.getTablaDatos().getColumnModel().getColumn(3).setCellEditor(new CellEditorCalendar());
        panelEstados.getTablaDatos().getColumnModel().getColumn(2).setCellEditor(new CellEditorCbEstado());
        panelEstados.getTablaDatos().getColumnModel().getColumn(1).setCellRenderer(new CellRendererImageEstado());        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabContenedor = new javax.swing.JTabbedPane();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tabContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(tabContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11))
        );

        tabContenedor.getAccessibleContext().setAccessibleName(org.openide.util.NbBundle.getMessage(FrmInfProyecto.class, "FrmInfProyecto.tabContenedor.AccessibleContext.accessibleName")); // NOI18N
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane tabContenedor;
    // End of variables declaration//GEN-END:variables
    private FrmPanel panelDocumentos=new FrmPanel(ViewLogin.picture.getIconProject16(),"");
    private FrmPanel panelEstudiantes=new FrmPanel(ViewLogin.picture.getIconProject16(),"");
    private FrmPanel panelDocentes=new FrmPanel(ViewLogin.picture.getIconProject16(),"");
    private FrmPanel panelEstados=new FrmPanel(ViewLogin.picture.getIconProject16(),"");
    private JButton btnAddDoc=new JButton(ViewLogin.picture.getIconAgregar());
    private JButton btnCommitDoc=new JButton(ViewLogin.picture.getIconCommit());
    private JButton btnRollbackDoc=new JButton(ViewLogin.picture.getIconRollBack());
    private JButton btnAddEst=new JButton(ViewLogin.picture.getIconAgregar());
    private JButton btnCommitEst=new JButton(ViewLogin.picture.getIconCommit());
    private JButton btnRollbackEst=new JButton(ViewLogin.picture.getIconRollBack());
    private JButton btnAddDoce=new JButton(ViewLogin.picture.getIconAgregar());
    private JButton btnCommitDoce=new JButton(ViewLogin.picture.getIconCommit());
    private JButton btnRollbackDoce=new JButton(ViewLogin.picture.getIconRollBack());
    private JButton btnAddEsta=new JButton(ViewLogin.picture.getIconAgregar());
    private JButton btnCommitEsta=new JButton(ViewLogin.picture.getIconCommit());
    private JButton btnRollbackEsta=new JButton(ViewLogin.picture.getIconRollBack());
    private TableModelDocumento modeldoc=new TableModelDocumento();
    private TableModelAlumno modelalum=new TableModelAlumno();
    private TableModelProfesor modelprof=new TableModelProfesor();
    private TableModelEstadoProy modelestproy=new TableModelEstadoProy();

    public TableModelEstadoProy getModelestproy() {
        return modelestproy;
    }

    public void setModelestproy(TableModelEstadoProy modelestproy) {
        this.modelestproy = modelestproy;
    }
    
    
    public JButton getBtnAddDoc() {
        return btnAddDoc;
    }

    public void setBtnAddDoc(JButton btnAddDoc) {
        this.btnAddDoc = btnAddDoc;
    }

    public JButton getBtnAddDoce() {
        return btnAddDoce;
    }

    public void setBtnAddDoce(JButton btnAddDoce) {
        this.btnAddDoce = btnAddDoce;
    }

    public JButton getBtnAddEst() {
        return btnAddEst;
    }

    public void setBtnAddEst(JButton btnAddEst) {
        this.btnAddEst = btnAddEst;
    }

    public JButton getBtnAddEsta() {
        return btnAddEsta;
    }

    public void setBtnAddEsta(JButton btnAddEsta) {
        this.btnAddEsta = btnAddEsta;
    }

    public JButton getBtnCommitDoc() {
        return btnCommitDoc;
    }

    public void setBtnCommitDoc(JButton btnCommitDoc) {
        this.btnCommitDoc = btnCommitDoc;
    }

    public JButton getBtnCommitDoce() {
        return btnCommitDoce;
    }

    public void setBtnCommitDoce(JButton btnCommitDoce) {
        this.btnCommitDoce = btnCommitDoce;
    }

    public JButton getBtnCommitEst() {
        return btnCommitEst;
    }

    public void setBtnCommitEst(JButton btnCommitEst) {
        this.btnCommitEst = btnCommitEst;
    }

    public JButton getBtnCommitEsta() {
        return btnCommitEsta;
    }

    public void setBtnCommitEsta(JButton btnCommitEsta) {
        this.btnCommitEsta = btnCommitEsta;
    }

    public JButton getBtnRollbackDoc() {
        return btnRollbackDoc;
    }

    public void setBtnRollbackDoc(JButton btnRollbackDoc) {
        this.btnRollbackDoc = btnRollbackDoc;
    }

    public JButton getBtnRollbackDoce() {
        return btnRollbackDoce;
    }

    public void setBtnRollbackDoce(JButton btnRollbackDoce) {
        this.btnRollbackDoce = btnRollbackDoce;
    }

    public JButton getBtnRollbackEst() {
        return btnRollbackEst;
    }

    public void setBtnRollbackEst(JButton btnRollbackEst) {
        this.btnRollbackEst = btnRollbackEst;
    }

    public JButton getBtnRollbackEsta() {
        return btnRollbackEsta;
    }

    public void setBtnRollbackEsta(JButton btnRollbackEsta) {
        this.btnRollbackEsta = btnRollbackEsta;
    }

    public TableModelDocumento getModeldoc() {
        return modeldoc;
    }

    public void setModeldoc(TableModelDocumento modeldoc) {
        this.modeldoc = modeldoc;
    }

    public FrmPanel getPanelDocentes() {
        return panelDocentes;
    }

    public void setPanelDocentes(FrmPanel panelDocentes) {
        this.panelDocentes = panelDocentes;
    }

    public FrmPanel getPanelDocumentos() {
        return panelDocumentos;
    }

    public void setPanelDocumentos(FrmPanel panelDocumentos) {
        this.panelDocumentos = panelDocumentos;
    }

    public FrmPanel getPanelEstados() {
        return panelEstados;
    }

    public void setPanelEstados(FrmPanel panelEstados) {
        this.panelEstados = panelEstados;
    }

    public FrmPanel getPanelEstudiantes() {
        return panelEstudiantes;
    }

    public void setPanelEstudiantes(FrmPanel panelEstudiantes) {
        this.panelEstudiantes = panelEstudiantes;
    }

    public JTabbedPane getTabContenedor() {
        return tabContenedor;
    }

    public void setTabContenedor(JTabbedPane tabContenedor) {
        this.tabContenedor = tabContenedor;
    }

    public TableModelAlumno getModelalum() {
        return modelalum;
    }

    public void setModelalum(TableModelAlumno modelalum) {
        this.modelalum = modelalum;
    }

    public TableModelProfesor getModelprof() {
        return modelprof;
    }

    public void setModelprof(TableModelProfesor modelprof) {
        this.modelprof = modelprof;
    }        
    
}
