/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmInfDecano.java
 *
 * Created on 30-nov-2011, 11:46:43
 */
package com.gps.view;

import javax.swing.JLabel;
import javax.swing.event.EventListenerList;
import javax.swing.plaf.ComponentUI;

/**
 *
 * @author Administrador
 */
public class FrmInfDecano extends javax.swing.JPanel {

    /** Creates new form FrmInfDecano */
    public FrmInfDecano() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        universidad = new javax.swing.JLabel();
        lblFacultad = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblDocente = new javax.swing.JLabel();
        docente = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        facultad = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        escuela = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        inicio = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        fin = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        estado = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblGrado = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(FrmInfDecano.class, "FrmInfDecano.border.title"))); // NOI18N

        universidad.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        universidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        universidad.setText(org.openide.util.NbBundle.getMessage(FrmInfDecano.class, "FrmInfDecano.universidad.text")); // NOI18N

        lblFacultad.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblFacultad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFacultad.setText(org.openide.util.NbBundle.getMessage(FrmInfDecano.class, "FrmInfDecano.lblFacultad.text")); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(org.openide.util.NbBundle.getMessage(FrmInfDecano.class, "FrmInfDecano.jLabel1.text")); // NOI18N

        lblDocente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDocente.setText(org.openide.util.NbBundle.getMessage(FrmInfDecano.class, "FrmInfDecano.lblDocente.text")); // NOI18N

        docente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        docente.setText(org.openide.util.NbBundle.getMessage(FrmInfDecano.class, "FrmInfDecano.docente.text")); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText(org.openide.util.NbBundle.getMessage(FrmInfDecano.class, "FrmInfDecano.jLabel2.text")); // NOI18N

        facultad.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        facultad.setText(org.openide.util.NbBundle.getMessage(FrmInfDecano.class, "FrmInfDecano.facultad.text")); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText(org.openide.util.NbBundle.getMessage(FrmInfDecano.class, "FrmInfDecano.jLabel4.text")); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText(org.openide.util.NbBundle.getMessage(FrmInfDecano.class, "FrmInfDecano.jLabel5.text")); // NOI18N

        escuela.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        escuela.setText(org.openide.util.NbBundle.getMessage(FrmInfDecano.class, "FrmInfDecano.escuela.text")); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText(org.openide.util.NbBundle.getMessage(FrmInfDecano.class, "FrmInfDecano.jLabel7.text")); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText(org.openide.util.NbBundle.getMessage(FrmInfDecano.class, "FrmInfDecano.jLabel8.text")); // NOI18N

        inicio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        inicio.setText(org.openide.util.NbBundle.getMessage(FrmInfDecano.class, "FrmInfDecano.inicio.text")); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText(org.openide.util.NbBundle.getMessage(FrmInfDecano.class, "FrmInfDecano.jLabel10.text")); // NOI18N

        fin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        fin.setText(org.openide.util.NbBundle.getMessage(FrmInfDecano.class, "FrmInfDecano.fin.text")); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText(org.openide.util.NbBundle.getMessage(FrmInfDecano.class, "FrmInfDecano.jLabel12.text")); // NOI18N

        estado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        estado.setText(org.openide.util.NbBundle.getMessage(FrmInfDecano.class, "FrmInfDecano.estado.text")); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText(org.openide.util.NbBundle.getMessage(FrmInfDecano.class, "FrmInfDecano.jLabel3.text")); // NOI18N

        lblGrado.setText(org.openide.util.NbBundle.getMessage(FrmInfDecano.class, "FrmInfDecano.lblGrado.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(universidad, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(lblFacultad, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(29, 29, 29)
                        .addComponent(lblGrado, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDocente)
                        .addGap(18, 18, 18)
                        .addComponent(docente, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(facultad, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(23, 23, 23)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(escuela, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(21, 21, 21)
                        .addComponent(jLabel8)
                        .addGap(6, 6, 6)
                        .addComponent(inicio, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel10)
                        .addGap(10, 10, 10)
                        .addComponent(fin, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(estado, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(universidad)
                .addGap(6, 6, 6)
                .addComponent(lblFacultad)
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(lblGrado, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblDocente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(docente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(facultad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(escuela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(estado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel docente;
    private javax.swing.JLabel escuela;
    private javax.swing.JLabel estado;
    private javax.swing.JLabel facultad;
    private javax.swing.JLabel fin;
    private javax.swing.JLabel inicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblDocente;
    private javax.swing.JLabel lblFacultad;
    private javax.swing.JLabel lblGrado;
    private javax.swing.JLabel universidad;
    // End of variables declaration//GEN-END:variables

    public JLabel getDocente() {
        return docente;
    }

    public void setDocente(JLabel docente) {
        this.docente = docente;
    }

    public JLabel getEscuela() {
        return escuela;
    }

    public void setEscuela(JLabel escuela) {
        this.escuela = escuela;
    }

    public JLabel getEstado() {
        return estado;
    }

    public void setEstado(JLabel estado) {
        this.estado = estado;
    }

    public JLabel getFacultad() {
        return facultad;
    }

    public void setFacultad(JLabel facultad) {
        this.facultad = facultad;
    }

    public JLabel getFin() {
        return fin;
    }

    public void setFin(JLabel fin) {
        this.fin = fin;
    }

    public JLabel getInicio() {
        return inicio;
    }

    public void setInicio(JLabel inicio) {
        this.inicio = inicio;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel10() {
        return jLabel10;
    }

    public void setjLabel10(JLabel jLabel10) {
        this.jLabel10 = jLabel10;
    }

    public JLabel getjLabel12() {
        return jLabel12;
    }

    public void setjLabel12(JLabel jLabel12) {
        this.jLabel12 = jLabel12;
    }

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getjLabel4() {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public void setjLabel5(JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    public JLabel getjLabel7() {
        return jLabel7;
    }

    public void setjLabel7(JLabel jLabel7) {
        this.jLabel7 = jLabel7;
    }

    public JLabel getjLabel8() {
        return jLabel8;
    }

    public void setjLabel8(JLabel jLabel8) {
        this.jLabel8 = jLabel8;
    }

    public JLabel getLblDocente() {
        return lblDocente;
    }

    public void setLblDocente(JLabel lblDocente) {
        this.lblDocente = lblDocente;
    }

    public JLabel getLblFacultad() {
        return lblFacultad;
    }

    public void setLblFacultad(JLabel lblFacultad) {
        this.lblFacultad = lblFacultad;
    }

    public JLabel getUniversidad() {
        return universidad;
    }

    public void setUniversidad(JLabel universidad) {
        this.universidad = universidad;
    }

    public EventListenerList getListenerList() {
        return listenerList;
    }

    public void setListenerList(EventListenerList listenerList) {
        this.listenerList = listenerList;
    }

    public ComponentUI getUi() {
        return ui;
    }

    public void setUi(ComponentUI ui) {
        this.ui = ui;
    }

    public JLabel getLblGrado() {
        return lblGrado;
    }

    public void setLblGrado(JLabel lblGrado) {
        this.lblGrado = lblGrado;
    }
    
    

}
